"""write_tools tool — generates tools.py with custom @tool functions."""

from pathlib import Path
from typing import Any

from claude_agent_sdk import tool

TOOLS_HEADER = '''\
"""Custom tools for this agent — generated by Agent Builder."""

from typing import Any

from claude_agent_sdk import tool, create_sdk_mcp_server, ToolAnnotations

TEST_MODE = False
'''


EMPTY_TOOLS_BODY = '''\
# This agent defines no custom tools. tools_server is intentionally empty
# so the generated agent.py can still `from tools import tools_server`.
tools_server = create_sdk_mcp_server(
    name="agent-tools",
    version="1.0.0",
    tools=[],
)
'''


async def write_tools(args: dict[str, Any], output_base: str = "output") -> dict[str, Any]:
    agent_name = args["agent_name"]
    tools_code = (args.get("tools_code") or "").strip()
    agent_dir = Path(output_base) / agent_name

    if not agent_dir.exists():
        return {
            "content": [{"type": "text", "text": f"Agent directory not found: {agent_dir}"}],
            "is_error": True,
        }

    if not tools_code:
        body = EMPTY_TOOLS_BODY
        suffix = " (empty stub — no custom tools)"
    else:
        body = tools_code
        suffix = ""

    full_content = TOOLS_HEADER + "\n" + body
    (agent_dir / "tools.py").write_text(full_content, encoding="utf-8")

    return {
        "content": [
            {
                "type": "text",
                "text": f"Wrote tools.py for '{agent_name}' ({len(full_content)} chars){suffix}",
            }
        ]
    }


write_tools_tool = tool(
    "write_tools",
    "Generate tools.py with custom @tool functions for a generated agent. "
    "tools_code must contain all @tool decorated functions (each with an if TEST_MODE: branch) "
    "and a create_sdk_mcp_server() call at the bottom assigning to tools_server.",
    {"agent_name": str, "tools_code": str},
)(write_tools)
