"""write_tools tool — generates tools.py with custom @tool functions."""

from pathlib import Path
from typing import Any

from claude_agent_sdk import tool

TOOLS_HEADER = '''\
"""Custom tools for this agent — generated by Agent Builder."""

from typing import Any

from claude_agent_sdk import tool, create_sdk_mcp_server, ToolAnnotations

TEST_MODE = False
'''


async def write_tools(args: dict[str, Any], output_base: str = "output") -> dict[str, Any]:
    agent_name = args["agent_name"]
    tools_code = args["tools_code"]
    agent_dir = Path(output_base) / agent_name

    if not agent_dir.exists():
        return {
            "content": [{"type": "text", "text": f"Agent directory not found: {agent_dir}"}],
            "is_error": True,
        }

    full_content = TOOLS_HEADER + "\n" + tools_code
    (agent_dir / "tools.py").write_text(full_content, encoding="utf-8")

    return {
        "content": [
            {
                "type": "text",
                "text": f"Wrote tools.py for '{agent_name}' ({len(full_content)} chars)",
            }
        ]
    }


write_tools_tool = tool(
    "write_tools",
    "Generate tools.py with custom @tool functions for a generated agent. "
    "tools_code must contain all @tool decorated functions (each with an if TEST_MODE: branch) "
    "and a create_sdk_mcp_server() call at the bottom assigning to tools_server.",
    {"agent_name": str, "tools_code": str},
)(write_tools)
